#!/bin/sh

loss="$(\
    warp-cli warp-stats | \
    sed "4q;d" | \
    grep --only-matching -E "([[:digit:]]).+" \
  )"

[ "$loss" = "" ] && echo "$loss" && exit 0

echo $(\
    echo "\
      { \
        \"full_text\": \"WL $loss\", \
        \"color\": \"#FFFF00\" \
      }, \
    " | sed -E "s/ {2,}//g")
