#!/bin/sh

loss="$(\
    warp-cli warp-stats | \
    sed "5q;d" | \
    sed s"/.$//" | \
    grep --only-matching -E "([[:digit:]]).+" \
  )"

[ "$loss" = "" ] && echo "$loss" && exit 0

echo $(\
    echo "\
      { \
        \"full_text\": \"WLoss $loss\", \
        \"color\": \"#FF0000\" \
      }, \
    " | sed -E "s/ {2,}//g")
