#!/bin/sh


# the list of modules to be loaded
modules=" 
  i3message \
  capslock \
  warp \
  lang \
  uptime \
  "


MODULES_DIR="~/projects/scripts/i3sm/modules"


# remove extra and trailing spaces
modules=$(echo $modules | \
  sed -E "s/ +/ /g" | \
  sed -E "s/^ | $//g" \
)


JSON=""
# join the output of the modules
for module in $modules; do
  moduleCommand="dash -c $MODULES_DIR/$module"
  moduleJSON="$(timeout 0.5s $moduleCommand)"
  JSON="${JSON}${moduleJSON}"
done


echo $JSON
