#!/bin/bash

MONEY=/home/mohamedwafy/Desktop/money_cli/money

val="$( \
  $MONEY budget | \
  grep "Allowed to spend today: " | \
  sed 's/Allowed to spend today: //'
  )"

echo "{ \"full_text\": \"MAS $val\" },"
